dist: xenial
notifications:
  email: false
language: python
python:
- 3.6
install:
- pip install -e .
script: python -c 'import sys; sys.exit(0)'
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: OpenXbox
  password:
    secure: DAO+lbmWqN36YhVWQIP+VhuzTFA7Drka+HQewTrc6CoP8YPDxQU4rBRFd56bEWAOg387w7XUdfRl3eysgMV7/YyoXtbUlXZqaru3OtwtZIrW3cPhQX2pL/KcBEYpPgxMgoKvZkAr/5ZP8DQUy2k+d+ztvu4w3O3Rvvb8Z689VAX/IPz7GXo4ICPGCv4zyyHUBct4MmdWbQ7O+dr5B/cugxkQqSh4PPR7u8++tGscTv6eVNc+0zzVLqx2j8ouUQaFcrDNx9LyGs+wvKBX+r3RQD10VSlAa+QDjYmqN5rYcGpqRGXmAsWmuGbHdkUBcgL6kJKA4u572Q1autfGRJoP+v04VWj42E33qmw/6Oapn9NJ9BkymkuUrCjcoNl01hdnkoDeQ46t+iUL6jlyouEqKQnvvcoqW+8Z5G4Wf2zziq1AiS4kTozKDLfQH4JUUy52Bwa52xtYxuyryw8aU+HBwBXCVgZOIgcUdRqTYSxEouzl8Tg4Y5fnrFCLmdxNAVUtDefdJUBVZy74YKigcIXHqJRMVtoMfZvEDAAb5PopVUuwF+GezBtxqo/TD8cpzMyE+HgQ2ZyivsAGGMOSHG3mglpionH0EwTsdDT7VzMAgxsUyvgYjSN5FW65gdueIhC31i0qdA3cvFBp5/k1gwtqZ6YQEBlNpuLVwEpvRI5KHKY=
  on:
    tags: true
    branch: master
    python: 3.6
